---
k3s_version: v1.17.5+k3s1
ansible_user: root
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--disable traefik" # Désactivation de traefik comme ingress car nous allons utiliser l'ingress d'istio
extra_agent_args: ""
