apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: create-service-on-labpod
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: resource
      eventName: example
  triggers:
    - template:
        name: argo-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Service
              metadata:
                name: -lab
                namespace: jupyterhub
              spec:
                ports:
                - port: 4040
                  name: http-sparkui
                - port: 6060
                  name: tcp-blockmanager
                - port: 2020
                  name: tcp-driver
                selector:
                  hub.jupyter.org/username: default
      parameters:
        - src:
            dependencyName: test-dep
            dataKey: body.metadata.annotations.hub\.jupyter\.org\/username
          dest: k8s.source.resource.spec.selector.hub\.jupyter\.org\/username
        - src:
            dependencyName: test-dep
            dataKey: body.metadata.annotations.hub\.jupyter\.org\/username
          dest: k8s.source.resource.metadata.name
          operation: prepend