apiVersion: v1
kind: Service
metadata:
  name: submarine-mlflow-service
  namespace: submarine-core
  labels:
    app: submarine-mlflow-service
spec:
  type: ExternalName
  externalName: mariadb.mariadb.svc.cluster.local
  ports:
  - port: 80
