apiVersion: apps/v1
kind: Deployment
metadata:
  name: submarine-server
  namespace: submarine-core
  labels:
    app: submarine-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submarine-server
  template:
    metadata:
      labels:
        app: submarine-server
    spec:
      containers:
      - name: server
        image: apache/submarine:server-0.6.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: SUBMARINE_SERVER_PORT
            value: "8080"
          - name: SUBMARINE_SERVER_PORT_8080_TCP
            value: "8080"
          - name: K8S_APISERVER_URL
            value: "kubernetes.default.svc"
        limits:
        volumeMounts:
        - name: config
          mountPath: "/opt/submarine-current/conf/submarine-site.xml"
          subPath: "submarine-site.xml"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: submarine-server-config