apiVersion: v1
kind: Service
metadata:
  name: submarine-server
  namespace: submarine-core
  labels:
    app: submarine-server
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: submarine-server
