apiVersion: batch/v1
kind: Job
metadata:
  name: submarine-databases-init-metastore
  namespace: default
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: submarine-initdb
        image: apache/submarine:database-0.6.0
        command: 
        - mysql
        - -uroot
        - -padmin
        - -hmariadb.mariadb.svc.cluster.local
        - submarine_metastore_db
        - -esource /tmp/database/metastore.sql;
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: submarine-databases-init-server
  namespace: default
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: submarine-initdb
        image: apache/submarine:database-0.6.0
        command: 
        - mysql
        - -uroot
        - -padmin
        - -hmariadb.mariadb.svc.cluster.local
        - submarine_server_db
        - -esource /tmp/database/submarine.sql; source /tmp/database/submarine-model.sql; source /tmp/database/submarine-data.sql;
      restartPolicy: Never