apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: resource
  namespace: jupyterhub
spec:
  template:
    serviceAccountName: argo-events-sa
    container:
      env:
        - name: DEBUG_LOG
          value: "true"
  dependencies:
    - name: test-dep
      eventSourceName: resource
      eventName: example
  triggers:
    - template:
        name: argo-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Service
              metadata:
                name: lab-
              spec:
                arguments:
                  parameters:
                  - name: username
                ports:
                - port: 8888
                  name: http
                - port: 4040
                  name: sparkui
                selector:
                  hub.jupyter.org/username: default
      parameters:
        - src:
            dependencyName: test-dep
            dataKey: body.metadata.annotations.hub\.jupyter\.org\/username
          dest: k8s.source.resource.spec.selector.hub\.jupyter\.org\/username
        - src:
            dependencyName: test-dep
            dataKey: body.metadata.annotations.hub\.jupyter\.org\/username
          dest: k8s.source.resource.metadata.name
          operation: append