apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: resource
  namespace: jupyterhub
spec:
  template:
    serviceAccountName: argo-events-sa
  resource:
    example:
      namespace: jupyterhub
      group: ""
      version: v1
      resource: pods
      eventTypes:
        - ADD
      filter:
        afterStart: true
        labels:
          - key: component
            operation: "=="
            value: singleuser-server